// entrypoints/popup/shared/components/RotatingSphere/RotatingSphere.tsx
export default function RotatingSphere() {
  return (
    <div className="wrap">
      <div className="inner"></div>
      <div className="x">
        <div className="x1"></div>
        <div className="x2"></div>
        <div className="xInner"></div>
        <div className="y"></div>
        <div className="y1"></div>
        <div className="y2"></div>
        <div className="yInner"></div>
        <div className="z"></div>
        <div className="z1"></div>
        <div className="z2"></div>
        <div className="zInner"></div>
      </div>
    </div>
  );
}

// src/app/shared/components/rotating-sphere/rotating-sphere.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'rotating-sphere',
  imports: [],
  templateUrl: './rotating-sphere.component.html',
  styleUrl: './rotating-sphere.component.scss',
})
export class RotatingSphereComponent { }

<div class="wrap">
  <div class="inner"></div>
  <div class="x">
    <div class="x1"></div>
    <div class="x2"></div>
    <div class="xInner"></div>
    <div class="y"></div>
    <div class="y1"></div>
    <div class="y2"></div>
    <div class="yInner"></div>
    <div class="z"></div>
    <div class="z1"></div>
    <div class="z2"></div>
    <div class="zInner"></div>
  </div>
</div>
